# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: manipulator
  joint_model_group_pose: stand
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Servo_Joint_1
    - Servo_Joint_2
    - Servo_Joint_3
    - Servo_Joint_4
    - Servo_Joint_5
    - End_Effector_Joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: bobert_control
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - Servo_Joint_1
      - Servo_Joint_2
      - Servo_Joint_3
      - Servo_Joint_4
      - Servo_Joint_5
      - End_Effector_Joint